:wrench: #1 - Modify to be separate theme.
maykinmedia/jekyll-theme-vng pull request #1
Opened 2018-11-12 09:56 UTC by svenvandescheur

2018-11-12 15:09 UTC, joeribekker requested changes

2018-11-12 15:09 UTC, joeribekker commented on _config.yml
> -title: Advanced Jekyll Theme
Waarom gaat dit er uit? Lijkt me onderdeel van het thema.

2018-11-12 15:09 UTC, joeribekker commented on _layouts/default.html
> +                <img class="img-fluid d-block my-0 mx-auto" {% if source %} src="{{ source }}" {% else %} src="/assets/img/default-image.jpg" {% endif %}>
Hoe zouden we nu eventueel plaatjes kunnen configureren?

2018-11-12 15:09 UTC, joeribekker commented on _layouts/default.html
> -            </div>
Kan je dit weer aanzetten maar dan met een linkje naar Github repo die configureerbaar is? De Twitter en Facebook mogen weg.

2018-11-12 15:59 UTC, svenvandescheur commented on _layouts/default.html
> +                <img class="img-fluid d-block my-0 mx-auto" {% if source %} src="{{ source }}" {% else %} src="/assets/img/default-image.jpg" {% endif %}>
Door `header-img` mee te geven in de config van de page. Wat dit doet is in plaats van een lelijke placeholder een fallback image tonen. Dit omdat de oude content geen `header-img` specificeert.

2018-11-12 15:59 UTC, svenvandescheur commented on _config.yml
> -title: Advanced Jekyll Theme
whoops

2018-11-13 09:04 UTC, joeribekker approved these changes

2018-11-13 09:04 UTC, merged